service: serverless-express

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  expressApp:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  usersPost:
    handler: src/handlers/api/users.postUsers
    events:
      - http:
          method: post
          path: /api/users
          integration: lambda
          request:
            schema:
              application/json: ${file(src/schemas/newUser.json)}
          response:
            headers:
              Content-Type: "'application/json'"
            statusCodes:
              201:
                pattern: ''
              200:
                pattern: .*is already taken.*
                template:
                  application/json: ${file(src/errors/error-response-template.yml)} # JSON return object